language: objective-c
   
before_install:    
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'

before_script:
    pod install

osx_image: xcode7.2

notifications:
  slack: unii:uiIBwCLf7BZh2scuao41N9by

script:    
    xctool -workspace SocialChallenge.xcworkspace -scheme SocialChallenge build -sdk iphonesimulator
